pipeline {
    agent any
    tools {
        maven 'Maven' //引号里的Maven不要改
    }
    stages {
        stage('Test') {
            steps {
                withSonarQubeEnv('SonarQube') { //引号里的SonarQube不要改
                    sh 'mvn clean sonar:sonar'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn package'
                archive 'target/WineTasters_I.war' //制品路径需要修改
            }
        }
        stage('Deploy') {
            steps { //所有的group1_demo需要修改
                sh 'docker stop WineTasters_WineTasters_I || true'
                sh 'docker rm WineTasters_WineTasters_I || true'
                sh 'docker run --name WineTasters_WineTasters_I -p 76667:8080 -d dordoka/tomcat' //端口11111需要修改
                sh 'docker cp target/WineTasters_I.war WineTasters_WineTasters_I:/opt/tomcat/webapps/' //制品路径需要修改
            }
        }
    }
}
